In [19]:
import pandas as pd
from sqlalchemy import create_engine

In [3]:
csv_file = "./data/TRI_Facility_Info_Chicago.csv"
facility_data_df = pd.read_csv(csv_file)
facility_data_df.head()

,_TRI_FACILITY_EZ.TRI_FACILITY_ID,V_TRI_FACILITY_EZ.FACILITY_NAME,V_TRI_FACILITY_EZ.STREET_ADDRESS,V_TRI_FACILITY_EZ.CITY_NAME,V_TRI_FACILITY_EZ.COUNTY_NAME,V_TRI_FACILITY_EZ.STATE_COUNTY_FIPS_CODE,V_TRI_FACILITY_EZ.STATE_ABBR,V_TRI_FACILITY_EZ.ZIP_CODE,V_TRI_FACILITY_EZ.REGION,V_TRI_FACILITY_EZ.FAC_CLOSED_IND,...,V_TRI_FACILITY_EZ.COLLECT_MTH_CODE,V_TRI_FACILITY_EZ.ACCURACY_VALUE,V_TRI_FACILITY_EZ.ACCURACY_SCORE,V_TRI_FACILITY_EZ.HDATUM_DESC,V_TRI_FACILITY_EZ.SCALE,V_TRI_FACILITY_EZ.SOURCE_DESC,V_TRI_FACILITY_EZ.SOURCE_CODE,V_TRI_FACILITY_EZ.CONVEYOR,V_TRI_FACILITY_EZ.BIA_CODE,V_TRI_FACILITY_EZ.TRIBE
0,60632CPTLM3801W,CAPITOL MANUFACTURING CHICAGO FACILITY,3801 W 44TH ST,CHICAGO,COOK,17031,IL,60632,5,0,...,1.0,30.0,99999999,NAD83,NaN,NaN,82.0,FRS-TRIS,NaN,NaN
1,60622MTRLS900NP,MATERIAL SERVICE CORP YARD 1,901 N SANGAMON ST,CHICAGO,COOK,17031,IL,60622,5,1,...,1.0,50.0,99999999,NAD83,NaN,NaN,82.0,FRS-TRIS,NaN,NaN
2,60632BRKSH4950S,BERKSHIRE FURNITURE INC,4950 S KILBOURN AVE,CHICAGO,COOK,17031,IL,60632,5,1,...,1.0,30.0,30,NAD83,NaN,NaN,82.0,FRS-GEOCODE,NaN,NaN
3,6063WNDPND6226W,INDEPENDENCE TUBE C,6226 W 74TH ST,CHICAGO,COOK,17031,IL,60638,5,0,...,1.0,30.0,30,NAD83,NaN,NaN,82.0,FRS-GEOCODE,NaN,NaN
4,60608MDWST1414S,MIDWEST FOLDING PRODUCTS,1414 S WESTERN AVE,CHICAGO,COOK,17031,IL,60608,5,0,...,19.0,20.0,99999999,NAD83,12000.0,NaN,17.0,FRS-TRIS,NaN,NaN

In [5]:
renamed_facility_df = facility_data_df.rename(columns={"_TRI_FACILITY_EZ.TRI_FACILITY_ID":"Facility_ID", 
                                                       "V_TRI_FACILITY_EZ.FACILITY_NAME":"Facility_Name", 
                                                       "V_TRI_FACILITY_EZ.STREET_ADDRESS": "Address", 
                                                       "V_TRI_FACILITY_EZ.CITY_NAME": "City", 
                                                       "V_TRI_FACILITY_EZ.COUNTY_NAME": "County", 
                                                       "V_TRI_FACILITY_EZ.STATE_ABBR": "State", 
                                                       "V_TRI_FACILITY_EZ.ZIP_CODE" : "Zipcode", 
                                                       "V_TRI_FACILITY_EZ.REGION": "Region", 
                                                       "V_TRI_FACILITY_EZ.FAC_CLOSED_IND": "Closed?", 
                                                       "V_TRI_FACILITY_EZ.PARENT_CO_DB_NUM" : "Parent_Company_ID", 
                                                       "V_TRI_FACILITY_EZ.PARENT_CO_NAME": "Parent_Company_Name", 
                                                       "V_TRI_FACILITY_EZ.LATITUDE": "Latitude", 
                                                       "V_TRI_FACILITY_EZ.LONGITUDE": "Longitude" })
renamed_facility_df.head()

,Facility_ID,Facility_Name,Address,City,County,V_TRI_FACILITY_EZ.STATE_COUNTY_FIPS_CODE,State,Zipcode,Region,Closed?,...,V_TRI_FACILITY_EZ.COLLECT_MTH_CODE,V_TRI_FACILITY_EZ.ACCURACY_VALUE,V_TRI_FACILITY_EZ.ACCURACY_SCORE,V_TRI_FACILITY_EZ.HDATUM_DESC,V_TRI_FACILITY_EZ.SCALE,V_TRI_FACILITY_EZ.SOURCE_DESC,V_TRI_FACILITY_EZ.SOURCE_CODE,V_TRI_FACILITY_EZ.CONVEYOR,V_TRI_FACILITY_EZ.BIA_CODE,V_TRI_FACILITY_EZ.TRIBE
0,60632CPTLM3801W,CAPITOL MANUFACTURING CHICAGO FACILITY,3801 W 44TH ST,CHICAGO,COOK,17031,IL,60632,5,0,...,1.0,30.0,99999999,NAD83,NaN,NaN,82.0,FRS-TRIS,NaN,NaN
1,60622MTRLS900NP,MATERIAL SERVICE CORP YARD 1,901 N SANGAMON ST,CHICAGO,COOK,17031,IL,60622,5,1,...,1.0,50.0,99999999,NAD83,NaN,NaN,82.0,FRS-TRIS,NaN,NaN
2,60632BRKSH4950S,BERKSHIRE FURNITURE INC,4950 S KILBOURN AVE,CHICAGO,COOK,17031,IL,60632,5,1,...,1.0,30.0,30,NAD83,NaN,NaN,82.0,FRS-GEOCODE,NaN,NaN
3,6063WNDPND6226W,INDEPENDENCE TUBE C,6226 W 74TH ST,CHICAGO,COOK,17031,IL,60638,5,0,...,1.0,30.0,30,NAD83,NaN,NaN,82.0,FRS-GEOCODE,NaN,NaN
4,60608MDWST1414S,MIDWEST FOLDING PRODUCTS,1414 S WESTERN AVE,CHICAGO,COOK,17031,IL,60608,5,0,...,19.0,20.0,99999999,NAD83,12000.0,NaN,17.0,FRS-TRIS,NaN,NaN

In [12]:

#final_facility_df = renamed_facility_df.drop(columns=['V_TRI_FACILITY_EZ.STATE_COUNTY_FIPS_CODE', 
                                        #"V_TRI_FACILITY_EZ.MAIL_NAME",
                                        #"V_TRI_FACILITY_EZ.MAIL_STREET_ADDRESS", 
                                        #"V_TRI_FACILITY_EZ.MAIL_CITY", 
                                        #"V_TRI_FACILITY_EZ.MAIL_STATE_ABBR",
                                        #"V_TRI_FACILITY_EZ.MAIL_COUNTRY", 
                                        #"V_TRI_FACILITY_EZ.MAIL_ZIP_CODE",
                                        #"V_TRI_FACILITY_EZ.ASGN_AGENCY",
                                        #"V_TRI_FACILITY_EZ.ASGN_FEDERAL_IND",
                                        #"V_TRI_FACILITY_EZ.STANDARDIZED_PARENT_COMPANY",
                                        #"V_TRI_FACILITY_EZ.ASGN_PARTIAL_IND",
                                        #"V_TRI_FACILITY_EZ.ASGN_PUBLIC_CONTACT",
                                        #"V_TRI_FACILITY_EZ.ASGN_PUBLIC_PHONE",
                                        #"V_TRI_FACILITY_EZ.ASGN_PUBLIC_CONTACT_EMAIL",
                                        #"V_TRI_FACILITY_EZ.REGISTRY_ID",
                                        #"V_TRI_FACILITY_EZ.ASGN_PUBLIC_PHONE_EXT",
                                        #"V_TRI_FACILITY_EZ.REF_POINT_DESC",
                                        #"V_TRI_FACILITY_EZ.REF_POINT_CODE",
                                        #"V_TRI_FACILITY_EZ.COLLECT_DESC",
                                        #"V_TRI_FACILITY_EZ.COLLECT_MTH_CODE",
                                        #"V_TRI_FACILITY_EZ.ACCURACY_VALUE",
                                        #"V_TRI_FACILITY_EZ.ACCURACY_SCORE",
                                        #"V_TRI_FACILITY_EZ.HDATUM_DESC",
                                        #"V_TRI_FACILITY_EZ.SCALE",
                                        #"V_TRI_FACILITY_EZ.SOURCE_DESC",
                                        #"V_TRI_FACILITY_EZ.SOURCE_CODE",
                                        #"V_TRI_FACILITY_EZ.CONVEYOR",
                                        #"V_TRI_FACILITY_EZ.BIA_CODE",
                                        #"V_TRI_FACILITY_EZ.TRIBE"])

#final_facility_df.head()

In [10]:
final_facility_df = renamed_facility_df[["Facility_ID", 
                                           "Facility_Name", 
                                           "Address", 
                                           "City", 
                                           "County", 
                                           "State", 
                                           "Zipcode", 
                                           "Region", 
                                           "Closed?", 
                                           "Parent_Company_ID", 
                                           "Parent_Company_Name", 
                                           "Latitude", 
                                           "Longitude" ]].copy()
final_facility_df.head()

,Facility_ID,Facility_Name,Address,City,County,State,Zipcode,Region,Closed?,Parent_Company_ID,Parent_Company_Name,Latitude,Longitude
0,60632CPTLM3801W,CAPITOL MANUFACTURING CHICAGO FACILITY,3801 W 44TH ST,CHICAGO,COOK,IL,60632,5,0,3002268,HARSCO CORP,41.813410,-87.719570
1,60622MTRLS900NP,MATERIAL SERVICE CORP YARD 1,901 N SANGAMON ST,CHICAGO,COOK,IL,60622,5,1,1381284,GENERAL DYNAMICS CORP,41.898180,-87.651925
2,60632BRKSH4950S,BERKSHIRE FURNITURE INC,4950 S KILBOURN AVE,CHICAGO,COOK,IL,60632,5,1,7140064,LEGGETT & PLATT INC,41.803010,-87.735660
3,6063WNDPND6226W,INDEPENDENCE TUBE C,6226 W 74TH ST,CHICAGO,COOK,IL,60638,5,0,3446796,NUCOR CORP,41.757690,-87.773800
4,60608MDWST1414S,MIDWEST FOLDING PRODUCTS,1414 S WESTERN AVE,CHICAGO,COOK,IL,60608,5,0,128836661,SAGUS INTERNATIONAL,41.862236,-87.686898

In [13]:
csv_file = "./data/TRI_Submission_Chicago_CAS.csv"
submission_data_df = pd.read_csv(csv_file)
submission_data_df.head()

,_TRI_SUBMISSIONS_EZ.TRI_FACILITY_ID,V_TRI_SUBMISSIONS_EZ.FACILITY_NAME,V_TRI_SUBMISSIONS_EZ.DOC_CTRL_NUM,V_TRI_SUBMISSIONS_EZ.REPORTING_YEAR,V_TRI_SUBMISSIONS_EZ.CHEM_NAME,V_TRI_SUBMISSIONS_EZ.CAS_NUM,V_TRI_SUBMISSIONS_EZ.TRI_CHEM_ID,V_TRI_SUBMISSIONS_EZ.ACTIVE_DATE,V_TRI_SUBMISSIONS_EZ.INACTIVE_DATE,V_TRI_SUBMISSIONS_EZ.CARCINOGEN,...,V_TRI_SUBMISSIONS_EZ.FAC_CLOSED_IND,V_TRI_SUBMISSIONS_EZ.MAX_AMOUNT_OF_CHEM,V_TRI_SUBMISSIONS_EZ.ONE_TIME_RELEASE_QTY,V_TRI_SUBMISSIONS_EZ.GENERIC_CHEM_NAME,V_TRI_SUBMISSIONS_EZ.CAS_CHEM_NAME,V_TRI_SUBMISSIONS_EZ.PRIMARY_SIC_CODE,V_TRI_SUBMISSIONS_EZ.INDUSTRY_CODE,V_TRI_SUBMISSIONS_EZ.SIC_CODES,V_TRI_SUBMISSIONS_EZ.NAICS_CODES,V_TRI_SUBMISSIONS_EZ.PRIMARY_NAICS_CODE
0,60623BLLCT2001S,ABLE ELECTROPOLISHING CO INC,1.302200e+12,2002,NICKEL,7440-02-0,7440020,1987,9999,Y,...,0,3,NaN,NaN,NICKEL,3471,332,3471,3.328130e+05,332813
1,60623CNTRL3200S,BWAY CORP,1.311210e+12,2011,ETHYLBENZENE,100-41-4,100414,1987,9999,Y,...,0,3,NaN,NaN,ETHYLBENZENE,NaN,332,NaN,3.324390e+05,332439
2,60622NZDRC1087N,NAZDAR CHICAGO,1.307210e+12,2007,1 2 4-TRIMETHYLBENZENE,95-63-6,95636,1987,9999,N,...,1,3,NaN,NaN,1 2 4-TRIMETHYLBENZENE,NaN,325,NaN,3.259100e+05,325910
3,60609SFTYK1445W,CLEAN HARBORS RECYCLING SERVICES OF CHICAGO LLC,1.315210e+12,2015,TOLUENE,108-88-3,108883,1987,9999,N,...,0,5,0.0,NaN,TOLUENE,NaN,562,NaN,5.629200e+05,562920
4,60638DBRTC4700S,DAUBERT CHEMICAL CO,1.306200e+12,2006,METHANOL,67-56-1,67561,1987,9999,N,...,0,4,NaN,NaN,METHANOL,NaN,325,NaN,3.255200e+17,325520

In [16]:
renamed_submission_df = submission_data_df.rename(columns={"_TRI_SUBMISSIONS_EZ.TRI_FACILITY_ID":"Facility_ID", 
                                                       "V_TRI_SUBMISSIONS_EZ.FACILITY_NAME":"Facility_Name", 
                                                       "V_TRI_SUBMISSIONS_EZ.REPORTING_YEAR": "Year", 
                                                       "V_TRI_SUBMISSIONS_EZ.CHEM_NAME": "Chem_Name", 
                                                       "V_TRI_SUBMISSIONS_EZ.CAS_NUM": "CAS_Num", 
                                                       "V_TRI_SUBMISSIONS_EZ.TRI_CHEM_ID": "Chem_ID", 
                                                       "V_TRI_SUBMISSIONS_EZ.ACTIVE_DATE" : "Active_Date", 
                                                       "V_TRI_SUBMISSIONS_EZ.INACTIVE_DATE": "Inactive_Date", 
                                                       "V_TRI_SUBMISSIONS_EZ.CARCINOGEN": "Carcinogen?", 
                                                       "V_TRI_SUBMISSIONS_EZ.CLEAN_AIR" : "Clean_Air_Act?", 
                                                       "V_TRI_SUBMISSIONS_EZ.LIST_3350": "3350_Chem_List", 
                                                       "V_TRI_SUBMISSIONS_EZ.MAX_AMOUNT_OF_CHEM": "Max_lbs_chem_year", 
                                                       "V_TRI_SUBMISSIONS_EZ.CAS_CHEM_NAME": "CAS_Chem_Name",
                                                       "V_TRI_SUBMISSIONS_EZ.PRIMARY_SIC_CODE": "Primary_SIC_Code",
                                                       "V_TRI_SUBMISSIONS_EZ.INDUSTRY_CODE": "Industry_Code", 
                                                       "V_TRI_SUBMISSIONS_EZ.PRIMARY_NAICS_CODE": "Primary_NAICS_Code"})
renamed_submission_df.head()

,Facility_ID,Facility_Name,V_TRI_SUBMISSIONS_EZ.DOC_CTRL_NUM,Year,Chem_Name,CAS_Num,Chem_ID,Active_Date,Inactive_Date,Carcinogen?,...,V_TRI_SUBMISSIONS_EZ.FAC_CLOSED_IND,Max_lbs_chem_year,V_TRI_SUBMISSIONS_EZ.ONE_TIME_RELEASE_QTY,V_TRI_SUBMISSIONS_EZ.GENERIC_CHEM_NAME,CAS_Chem_Name,Primary_SIC_Code,Industry_Code,V_TRI_SUBMISSIONS_EZ.SIC_CODES,V_TRI_SUBMISSIONS_EZ.NAICS_CODES,Primary_NAICS_Code
0,60623BLLCT2001S,ABLE ELECTROPOLISHING CO INC,1.302200e+12,2002,NICKEL,7440-02-0,7440020,1987,9999,Y,...,0,3,NaN,NaN,NICKEL,3471,332,3471,3.328130e+05,332813
1,60623CNTRL3200S,BWAY CORP,1.311210e+12,2011,ETHYLBENZENE,100-41-4,100414,1987,9999,Y,...,0,3,NaN,NaN,ETHYLBENZENE,NaN,332,NaN,3.324390e+05,332439
2,60622NZDRC1087N,NAZDAR CHICAGO,1.307210e+12,2007,1 2 4-TRIMETHYLBENZENE,95-63-6,95636,1987,9999,N,...,1,3,NaN,NaN,1 2 4-TRIMETHYLBENZENE,NaN,325,NaN,3.259100e+05,325910
3,60609SFTYK1445W,CLEAN HARBORS RECYCLING SERVICES OF CHICAGO LLC,1.315210e+12,2015,TOLUENE,108-88-3,108883,1987,9999,N,...,0,5,0.0,NaN,TOLUENE,NaN,562,NaN,5.629200e+05,562920
4,60638DBRTC4700S,DAUBERT CHEMICAL CO,1.306200e+12,2006,METHANOL,67-56-1,67561,1987,9999,N,...,0,4,NaN,NaN,METHANOL,NaN,325,NaN,3.255200e+17,325520

In [17]:
final_submission_df = renamed_submission_df[["Facility_ID", 
                                         "Facility_Name", 
                                         "Year", 
                                         "Chem_Name", 
                                         "CAS_Num", 
                                         "Chem_ID", 
                                         "Active_Date", 
                                         "Inactive_Date", 
                                         "Carcinogen?", 
                                         "Clean_Air_Act?", 
                                         "3350_Chem_List", 
                                         "Max_lbs_chem_year", 
                                         "CAS_Chem_Name",
                                         "Primary_SIC_Code",
                                         "Industry_Code", 
                                         "Primary_NAICS_Code"]].copy()
final_submission_df.head()

,Facility_ID,Facility_Name,Year,Chem_Name,CAS_Num,Chem_ID,Active_Date,Inactive_Date,Carcinogen?,Clean_Air_Act?,3350_Chem_List,Max_lbs_chem_year,CAS_Chem_Name,Primary_SIC_Code,Industry_Code,Primary_NAICS_Code
0,60623BLLCT2001S,ABLE ELECTROPOLISHING CO INC,2002,NICKEL,7440-02-0,7440020,1987,9999,Y,Y,Y,3,NICKEL,3471,332,332813
1,60623CNTRL3200S,BWAY CORP,2011,ETHYLBENZENE,100-41-4,100414,1987,9999,Y,Y,N,3,ETHYLBENZENE,NaN,332,332439
2,60622NZDRC1087N,NAZDAR CHICAGO,2007,1 2 4-TRIMETHYLBENZENE,95-63-6,95636,1987,9999,N,N,N,3,1 2 4-TRIMETHYLBENZENE,NaN,325,325910
3,60609SFTYK1445W,CLEAN HARBORS RECYCLING SERVICES OF CHICAGO LLC,2015,TOLUENE,108-88-3,108883,1987,9999,N,Y,N,5,TOLUENE,NaN,562,562920
4,60638DBRTC4700S,DAUBERT CHEMICAL CO,2006,METHANOL,67-56-1,67561,1987,9999,N,Y,N,4,METHANOL,NaN,325,325520

In [29]:
rds_connection_string = "root:NLM71011@127.0.0.1/tri_chicago_db"
engine = create_engine(f'mysql://{rds_connection_string}')

In [30]:
final_facility_df.to_sql(name='facility', con=engine, if_exists='append', index=False)

In [31]:
final_submission_df.to_sql(name='submission', con=engine, if_exists='append', index=False)

In [ ]:
# Read XML from file
# filepath = "./data/hsdb.xml.20190428"
filepath = os.path.join(".", "data", "hsdb.xml.20190428")
print(filepath)
with open(filepath) as file:
    xml = file.read()

In [ ]:
import xml.etree.ElementTree as ET

In [ ]:
tree = ET.parse(filepath)

In [ ]:
root = tree.getroot()

In [ ]:
root.tag

root.attrib

for child in root:
    print(child.tag, child.attrib)

root[0]

root[0][1]

for doc in root.findall("DOC"):
    #date = doc.find("date").text
    cas = doc.find("CASRegistryNumber").text
    print(cas)

print(cas)